export const packagesData= [
  {
    id: 1,
    destination: 'Paris',
    itinerary: 'Explore iconic landmarks...',
    price: 1000,
    accommodations: 'Luxury Hotel',
    ticketsAvailable: 10,
    ratings: [4, 5, 3],
  },
  {
    id: 2,
    destination: 'London',
    itinerary: 'Explore iconic landmarks...',
    price: 1000,
    accommodations: 'Luxury Hotel',
    ticketsAvailable: 10,
    ratings: [4, 5, 3],
  },{
    id: 3,
    destination: 'Japan',
    itinerary: 'Explore iconic landmarks...',
    price: 1000,
    accommodations: 'Luxury Hotel',
    ticketsAvailable: 10,
    ratings: [4, 5, 3],
  },{
    id: 4,
    destination: 'Mexico',
    itinerary: 'Explore iconic landmarks...',
    price: 1000,
    accommodations: 'Luxury Hotel',
    ticketsAvailable: 10,
    ratings: [4, 5, 3],
  },
]; 